/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

/**
 *
 * @author Nirala Kumar
 */
public class UserMain extends javax.swing.JFrame {

    /**
     * Creates new form UserMain
     */
    public UserMain() {
        initComponents();
        this.setSize(900, 600);
        this.setBounds(350, 130, 900, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ubookingBtn = new javax.swing.JButton();
        userBaBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        ubookingBtn.setBackground(new java.awt.Color(0, 102, 102));
        ubookingBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 14)); // NOI18N
        ubookingBtn.setForeground(new java.awt.Color(255, 255, 255));
        ubookingBtn.setText("My Bookings");
        ubookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubookingBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ubookingBtn);
        ubookingBtn.setBounds(506, 405, 270, 60);

        userBaBtn.setBackground(new java.awt.Color(0, 102, 102));
        userBaBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 14)); // NOI18N
        userBaBtn.setForeground(new java.awt.Color(255, 255, 255));
        userBaBtn.setText("Book Advertisement");
        userBaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(userBaBtn);
        userBaBtn.setBounds(103, 405, 270, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/showorderdetailsicon.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(560, 200, 200, 200);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/productbookingicon.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 200, 200, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userBaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBaBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UserBookAdvertisement().setVisible(true);

    }//GEN-LAST:event_userBaBtnActionPerformed

    private void ubookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubookingBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UserBookingDetails().setVisible(true);
    }//GEN-LAST:event_ubookingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ubookingBtn;
    private javax.swing.JButton userBaBtn;
    // End of variables declaration//GEN-END:variables
}
