/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nirala Kumar
 */
public class AdminMain extends javax.swing.JFrame {

    /**
     * Creates new form AdminMain
     */
    public AdminMain() {
        initComponents();
        this.setSize(900, 600);
        this.setBounds(350, 130, 900, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        showCustDet = new javax.swing.JButton();
        showEmpDet = new javax.swing.JButton();
        addEmployees = new javax.swing.JButton();
        bookAd = new javax.swing.JButton();
        showBookAd = new javax.swing.JButton();
        addCustomers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.pink);
        setForeground(new java.awt.Color(0, 204, 204));
        setLocation(new java.awt.Point(350, 130));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        showCustDet.setBackground(new java.awt.Color(0, 51, 51));
        showCustDet.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 14)); // NOI18N
        showCustDet.setForeground(new java.awt.Color(255, 255, 255));
        showCustDet.setText("Show Customer's Details");
        showCustDet.setPreferredSize(new java.awt.Dimension(180, 180));
        showCustDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCustDetActionPerformed(evt);
            }
        });
        jPanel1.add(showCustDet);
        showCustDet.setBounds(340, 460, 260, 50);

        showEmpDet.setBackground(new java.awt.Color(0, 51, 51));
        showEmpDet.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 14)); // NOI18N
        showEmpDet.setForeground(new java.awt.Color(255, 255, 255));
        showEmpDet.setText("Show Employee Details");
        showEmpDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEmpDetActionPerformed(evt);
            }
        });
        jPanel1.add(showEmpDet);
        showEmpDet.setBounds(640, 460, 220, 50);

        addEmployees.setBackground(new java.awt.Color(0, 51, 51));
        addEmployees.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 14)); // NOI18N
        addEmployees.setForeground(new java.awt.Color(255, 255, 255));
        addEmployees.setText("Add New Employee");
        addEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeesActionPerformed(evt);
            }
        });
        jPanel1.add(addEmployees);
        addEmployees.setBounds(50, 460, 230, 49);

        bookAd.setBackground(new java.awt.Color(0, 51, 51));
        bookAd.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 14)); // NOI18N
        bookAd.setForeground(new java.awt.Color(255, 255, 255));
        bookAd.setText("Book Advertisement");
        bookAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAdActionPerformed(evt);
            }
        });
        jPanel1.add(bookAd);
        bookAd.setBounds(340, 200, 250, 49);

        showBookAd.setBackground(new java.awt.Color(0, 51, 51));
        showBookAd.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 14)); // NOI18N
        showBookAd.setForeground(new java.awt.Color(255, 255, 255));
        showBookAd.setText("Show Book Advertisement");
        showBookAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBookAdActionPerformed(evt);
            }
        });
        jPanel1.add(showBookAd);
        showBookAd.setBounds(650, 200, 210, 49);

        addCustomers.setBackground(new java.awt.Color(0, 51, 51));
        addCustomers.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 14)); // NOI18N
        addCustomers.setForeground(new java.awt.Color(255, 255, 255));
        addCustomers.setText("Add New Customer's");
        addCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomersActionPerformed(evt);
            }
        });
        jPanel1.add(addCustomers);
        addCustomers.setBounds(50, 200, 240, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 260, 200, 200);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addnewemployee.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 260, 200, 200);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employeeicon.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(650, 260, 200, 200);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addnewcustomersicon.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 50, 200, 150);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/productbookingicon.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 50, 200, 150);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/showorderdetailsicon.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(660, 50, 200, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 600);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(460, 300, 170, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomersActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Customers().setVisible(true);
    }//GEN-LAST:event_addCustomersActionPerformed

    private void addEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Employee().setVisible(true);
    }//GEN-LAST:event_addEmployeesActionPerformed

    private void bookAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAdActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BookAdvertisement().setVisible(true);
    }//GEN-LAST:event_bookAdActionPerformed

    private void showBookAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBookAdActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BookingDetails().setVisible(true);
    }//GEN-LAST:event_showBookAdActionPerformed

    private void showCustDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCustDetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ShowCustomerDetails().setVisible(true);
                
    }//GEN-LAST:event_showCustDetActionPerformed

    private void showEmpDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEmpDetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        
        
        new ShowEmployeeDetails().setVisible(true);
    }//GEN-LAST:event_showEmpDetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomers;
    private javax.swing.JButton addEmployees;
    private javax.swing.JButton bookAd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton showBookAd;
    private javax.swing.JButton showCustDet;
    private javax.swing.JButton showEmpDet;
    // End of variables declaration//GEN-END:variables
}
