/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.sql.*;
import java.util.regex.*;
import javax.swing.JOptionPane;
import user.UserMain;

/**
 *
 * @author Nirala Kumar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setSize(900, 600);
        this.setBounds(350, 130, 900, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        unameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        typeCkbox = new javax.swing.JCheckBox();
        createAccount = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 130));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setText("User Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(174, 98, 90, 30);

        unameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unameTxtKeyReleased(evt);
            }
        });
        getContentPane().add(unameTxt);
        unameTxt.setBounds(320, 99, 376, 30);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(174, 191, 90, 30);

        passTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passTxtKeyReleased(evt);
            }
        });
        getContentPane().add(passTxt);
        passTxt.setBounds(320, 192, 376, 30);

        loginBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), null, null));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn);
        loginBtn.setBounds(422, 355, 141, 32);

        typeCkbox.setBackground(new java.awt.Color(0, 204, 204));
        typeCkbox.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        typeCkbox.setText("Admin");
        getContentPane().add(typeCkbox);
        typeCkbox.setBounds(174, 283, 90, 30);

        createAccount.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        createAccount.setText("Create Account");
        createAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), null, null));
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });
        getContentPane().add(createAccount);
        createAccount.setBounds(422, 465, 141, 35);

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel3.setText("New User's");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(174, 465, 90, 35);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String name = unameTxt.getText().trim();
        String pass = new String(passTxt.getPassword()).trim();
        try {
            //Class.forName("com.mysql.jdbc.Driver");

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/adhaven", "root", "1234");
            String qry;
            if (!typeCkbox.isSelected()) {
                qry = "SELECT *FROM user where name=? and password=? and type='user'";

                PreparedStatement pr = conn.prepareStatement(qry);
                pr.setString(1, name);
                pr.setString(2, pass);
                ResultSet rst = pr.executeQuery();
                if (rst.next()) {
                    new UserMain().setVisible(true);
                    this.setVisible(false);
                }
            }
            if (typeCkbox.isSelected()) {
                qry = "SELECT *FROM user where name=? and password=? and type='admin'";
                PreparedStatement pr = conn.prepareStatement(qry);
                pr.setString(1, name);
                pr.setString(2, pass);
                ResultSet rst = pr.executeQuery();
                if (rst.next()) {
                    new AdminMain().setVisible(true);
                    this.setVisible(false);
                }
            }
            conn.close();
        } catch (Exception e) {

            e.printStackTrace();
        }

    }//GEN-LAST:event_loginBtnActionPerformed

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        // TODO add your handling code here:
        new NewUser().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_createAccountActionPerformed

    //username validation code 
    private void unameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameTxtKeyReleased
        // TODO add your handling code here:
        //Nirala8084
        String PATTERN = "^[a-zA-Z0-9 ]{0,30}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(unameTxt.getText().trim());
        if (!match.matches()) {
            JOptionPane.showMessageDialog(null, "Please Enter correct username");
            unameTxt.setText("");
        }
    }//GEN-LAST:event_unameTxtKeyReleased

    //password validation code
    private void passTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTxtKeyReleased
        // TODO add your handling code here:
        //Niralak025@,Niralak025$,Niralak025*,Niralak025#
        String PATTERN ="^[a-zA-Z0-9@$*#]{0,15}"; 
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match1 = patt.matcher(new String(passTxt.getPassword()).trim());
        if(!match1.matches()){
            JOptionPane.showMessageDialog(null, "Please Enter correct password");
            passTxt.setText("");
        }
    }//GEN-LAST:event_passTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JCheckBox typeCkbox;
    private javax.swing.JTextField unameTxt;
    // End of variables declaration//GEN-END:variables
}
