/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Nirala Kumar
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
        this.setSize(900, 600);
        this.setBounds(350, 130, 900, 600);
    }

    public static boolean nameValidation(String name) {
        return name.contains(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nuName = new javax.swing.JTextField();
        nuMail = new javax.swing.JTextField();
        nuMob = new javax.swing.JTextField();
        nuPassword = new javax.swing.JPasswordField();
        nuTypeCbox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        nuNextBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(128, 91, 91, 30);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(128, 159, 91, 32);

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel3.setText("Mobile No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(128, 230, 91, 32);

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(128, 313, 91, 31);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel5.setText("UserType");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(128, 390, 91, 31);

        nuName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nuNameKeyReleased(evt);
            }
        });
        getContentPane().add(nuName);
        nuName.setBounds(248, 91, 419, 30);

        nuMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nuMailKeyReleased(evt);
            }
        });
        getContentPane().add(nuMail);
        nuMail.setBounds(248, 159, 419, 32);

        nuMob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nuMobKeyReleased(evt);
            }
        });
        getContentPane().add(nuMob);
        nuMob.setBounds(248, 230, 419, 32);

        nuPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nuPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(nuPassword);
        nuPassword.setBounds(248, 313, 419, 31);

        nuTypeCbox.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        nuTypeCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select User Type---", "admin", "user", " " }));
        getContentPane().add(nuTypeCbox);
        nuTypeCbox.setBounds(248, 390, 419, 31);

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 18)); // NOI18N
        jLabel6.setText("New User ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 37, 266, 21);

        nuNextBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        nuNextBtn.setText("Next");
        nuNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuNextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nuNextBtn);
        nuNextBtn.setBounds(350, 500, 200, 50);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Password Format : Upper case/Lower case latter digit symbols(*,#,$,@) atmost 15 digits");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuNextBtnActionPerformed
        // TODO add your handling code here:
        String name = "";
        String nam = nuName.getText().trim();
        if (nameValidation(nam)) {
            name = nam;
        }
        String query = "INSERT INTO registeruser(name,email,mobile,password,usertype) VALUES(?,?,?,?,?)";

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/adhaven", "root", "1234");
            if (conn != null) {
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1, name);
                pst.setString(2, nuMail.getText().trim());
                pst.setString(3, nuMob.getText().trim());
                pst.setString(4, new String(nuPassword.getPassword()).trim());
                pst.setString(5, new String(nuTypeCbox.getSelectedItem().toString()));
                pst.executeUpdate();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        String query_2 = "INSERT INTO user(name,password,type) VALUES(?,?,?)";
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/adhaven", "root", "1234");
            if (conn != null) {
                PreparedStatement pst = conn.prepareStatement(query_2);
                pst.setString(1, nuName.getText().trim());
                pst.setString(2, new String(nuPassword.getPassword()).trim());
                pst.setString(3, new String(nuTypeCbox.getSelectedItem().toString()));
                pst.executeUpdate();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nuNextBtnActionPerformed

    private void nuNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuNameKeyReleased
        String PATTERN = "^[a-zA-Z ]{0,30}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(nuName.getText().trim());
        if (!match.matches()) {
            JOptionPane.showMessageDialog(null, "Please Enter correct Name");
            nuName.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_nuNameKeyReleased

    private void nuMailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuMailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9@.]{0,50}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(nuMail.getText().trim());
        if (!match.matches()) {
            JOptionPane.showMessageDialog(null, "Please Enter correct Email");
            nuMail.setText("");
        }
    }//GEN-LAST:event_nuMailKeyReleased

    private void nuMobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuMobKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,12}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(nuMob.getText().trim());
        if (!match.matches()) {
            JOptionPane.showMessageDialog(null, "Please Enter correct Mobile No");
            nuMob.setText("");
        }
    }//GEN-LAST:event_nuMobKeyReleased

    private void nuPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuPasswordKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[a-zA-Z0-9@$*#]{0,15}"; 
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match1 = patt.matcher(new String(nuPassword.getPassword()).trim());
        if(!match1.matches()){
            JOptionPane.showMessageDialog(null, "Please Enter correct password");
            nuPassword.setText("");
        }
    }//GEN-LAST:event_nuPasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nuMail;
    private javax.swing.JTextField nuMob;
    private javax.swing.JTextField nuName;
    private javax.swing.JButton nuNextBtn;
    private javax.swing.JPasswordField nuPassword;
    private javax.swing.JComboBox<String> nuTypeCbox;
    // End of variables declaration//GEN-END:variables
}
