/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nirala Kumar
 */
public class ShowCustomerDetails extends javax.swing.JFrame {

    /**
     * Creates new form ShowCustomerDetails
     */
    public ShowCustomerDetails() {
        initComponents();
        this.setSize(900, 600);
        this.setBounds(350, 130, 900, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        custdtable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        scdBackBtn = new javax.swing.JButton();
        showcustBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        custdtable.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        custdtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Mobile Number", "Addhar No", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(custdtable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 890, 402);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jPanel1.setLayout(null);

        scdBackBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        scdBackBtn.setText("Back");
        scdBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scdBackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(scdBackBtn);
        scdBackBtn.setBounds(600, 500, 200, 50);

        showcustBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        showcustBtn.setText("Show Details");
        showcustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showcustBtnActionPerformed(evt);
            }
        });
        jPanel1.add(showcustBtn);
        showcustBtn.setBounds(100, 500, 200, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scdBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scdBackBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AdminMain().setVisible(true);
                
    }//GEN-LAST:event_scdBackBtnActionPerformed

    private void showcustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showcustBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtr;
        dtr = (DefaultTableModel) custdtable.getModel();
        dtr.setRowCount(3);//initial value of row set 
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/adhaven", "root", "1234");
            if (conn != null) {

                PreparedStatement pst = conn.prepareStatement("SELECT * FROM customersdetails");
                ResultSet rst = pst.executeQuery();
                while (rst.next()) {
                    dtr.addRow(new Object[]{rst.getInt("id"), rst.getString("cname"), rst.getString("cemail"), rst.getString("cmob"),rst.getString("caddharno"),rst.getString("caddress")});
                } 

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_showcustBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowCustomerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable custdtable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton scdBackBtn;
    private javax.swing.JButton showcustBtn;
    // End of variables declaration//GEN-END:variables
}
